const Datas = [
    {
        id: 92,
        name: "Chicken Medium Wok Bowl",
        description: "Serves 1 | Serves 1 - choice of any 1 rice/noodles, 1 sauce, 6 vegetables and 2 seasoning.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/2eb56980ebef8185074e3ddcdae720a5",
        price: 339.0,
        type: "Non Veg",
        rating: "3.9",
        nutrition: {
            calories: 400,
            protein: 25,
            carbs: 50,
            sugars: 10,
            fiber: 5,
            fat: 15,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 75,
            sodium: 900,
            potassium: 400,
            vitaminA: 10,
            vitaminC: 25,
            calcium: 5,
            iron: 15
        }
    },
    {
        id: 17,
        name: "Combo for 1 Veg",
        description: "Serves 1 | Combo for one (Rice/Noodle Bowl with choice of Veg Gravy, Veg Momos & Drinks)",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/3e4f7ca32bf517b390f1cb3205b892e4",
        price: 359.0,
        type: "Veg",
        rating: "4.0",
        nutrition: {
            calories: 350,
            protein: 12,
            carbs: 60,
            sugars: 15,
            fiber: 8,
            fat: 10,
            saturatedFat: 2,
            transFat: 0,
            cholesterol: 0,
            sodium: 850,
            potassium: 300,
            vitaminA: 15,
            vitaminC: 30,
            calcium: 8,
            iron: 12
        }
    },
    {
        id: 20,
        name: "Schezwan Paneer Dry",
        description: "Serves 1 | (Spicy) Cubes Of Paneer, Onion, Capsicum Tossed With Schezwan Sauce.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/e3d760e8-a686-446b-887e-0a3256b077f4_1d4af440-1e94-440e-8e46-762968fb77a1.jpg_compressed",
        price: 199.0,
        type: "Veg",
        rating: "4.0",
        nutrition: {
            calories: 300,
            protein: 14,
            carbs: 25,
            sugars: 5,
            fiber: 5,
            fat: 20,
            saturatedFat: 8,
            transFat: 0,
            cholesterol: 30,
            sodium: 600,
            potassium: 250,
            vitaminA: 12,
            vitaminC: 20,
            calcium: 10,
            iron: 8
        }
    },
    {
        id: 19,
        name: "Black forest Mousse Cake",
        description: "Serves 1 | Evergreen cake recipe, served in a mousse style dessert",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/5/21/3aeaee91-6bce-45f1-bad4-0ee4da6e3fef_7a319038-77af-47d2-b67b-b5868a48f668.jpg_compressed",
        price: 89.0,
        type: "Veg",
        rating: "4.1",
        nutrition: {
            calories: 250,
            protein: 4,
            carbs: 35,
            sugars: 25,
            fiber: 2,
            fat: 12,
            saturatedFat: 6,
            transFat: 0,
            cholesterol: 20,
            sodium: 150,
            potassium: 100,
            vitaminA: 6,
            vitaminC: 10,
            calcium: 6,
            iron: 4
        }
    },
    {
        id: 12,
        name: "Combo for 1 Non-Veg",
        description: "Serves 1 | Combo for one (Rice/Noodle Bowl with choice of Non-Veg Gravy, Non- Veg Momos & Drinks)",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/440c06ace44b931b729d9b6a090aba07",
        price: 379.0,
        type: "Non Veg",
        rating: "4.3",
        nutrition: {
            calories: 420,
            protein: 28,
            carbs: 55,
            sugars: 12,
            fiber: 7,
            fat: 18,
            saturatedFat: 5,
            transFat: 0,
            cholesterol: 80,
            sodium: 950,
            potassium: 450,
            vitaminA: 10,
            vitaminC: 20,
            calcium: 6,
            iron: 14
        }
    },
    {
        id: 13,
        name: "Salted Caramel Choco Mousse",
        description: "Serves 1 | Layers of Salted Caramel mousse and Choco mousse served chilled",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/99e4d3ff-d474-4665-bc1b-25a172302149_836b958b-9e77-496c-a7a0-a1fc6d7cae2e.jpg_compressed",
        price: 79.0,
        type: "Veg",
        rating: "4.0",
        nutrition: {
            calories: 280,
            protein: 5,
            carbs: 35,
            sugars: 25,
            fiber: 2,
            fat: 12,
            saturatedFat: 6,
            transFat: 0,
            cholesterol: 25,
            sodium: 160,
            potassium: 120,
            vitaminA: 8,
            vitaminC: 12,
            calcium: 5,
            iron: 6
        }
    },
    {
        id: 15,
        name: "Schezwan Chicken Dry",
        description: "Serves 1 | (Spicy) Diced Chicken, Onion, Capsicum Tossed With Schezwan Sauce.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/ca939afd-fad4-48f0-b0e6-567c81c0f8b9_dc08e37f-95db-49ed-bf51-a876febf53df.jpg_compressed",
        price: 199.0,
        type: "Non Veg",
        rating: "4.7",
        nutrition: {
            calories: 350,
            protein: 26,
            carbs: 30,
            sugars: 8,
            fiber: 6,
            fat: 15,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 70,
            sodium: 850,
            potassium: 350,
            vitaminA: 8,
            vitaminC: 20,
            calcium: 5,
            iron: 10
        }
    },
    {
        id: 18,
        name: "Schezwan Chicken Bowl",
        description: "Serves 1 | (Spicy) Chicken & Veggies Tossed In Schezwan Sauce, Served With Choice Of Rice/ Noodle.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/c28757ca-2780-4843-84ec-b221312368dc_735fd348-fd94-419c-8169-21f9e9905a7f.jpg",
        price: 339.0,
        type: "Non Veg",
        rating: "4.3",
        nutrition: {
            calories: 400,
            protein: 30,
            carbs: 45,
            sugars: 10,
            fiber: 8,
            fat: 18,
            saturatedFat: 5,
            transFat: 0,
            cholesterol: 75,
            sodium: 900,
            potassium: 400,
            vitaminA: 10,
            vitaminC: 25,
            calcium: 6,
            iron: 12
        }
    },
    {
        id: 14,
        name: "Kung Pao Chicken Bowl",
        description: "Serves 1 | (Medium Spicy) Chicken & Veggies Tossed In Kung Pao Sauce, Served With Choice Of Rice/ Noodle.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/1449905f-a8ed-4f5c-8572-c13046bd23af_46b11a3d-d3bc-4020-8e5a-26a1392101bf.jpg_compressed",
        price: 340.0,
        type: "Non Veg",
        rating: "4.5",
        nutrition: {
            calories: 410,
            protein: 32,
            carbs: 50,
            sugars: 12,
            fiber: 9,
            fat: 17,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 70,
            sodium: 920,
            potassium: 450,
            vitaminA: 10,
            vitaminC: 30,
            calcium: 6,
            iron: 13
        }
    },
    {
        id: 11,
        name: "Fried Chicken Wheat Momos With Momo Chutney",
        description: "Serves 1 | Aromatic chicken mince encased & fried in wheat wrapper. Served with momo chutney",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/199514d6-77c2-4134-929a-94b97a799953_ba658061-7337-4cec-ad45-7ff8d7802589.jpg_compressed",
        price: 199.0,
        type: "Non Veg",
        rating: "4.2",
        nutrition: {
            calories: 320,
            protein: 22,
            carbs: 35,
            sugars: 5,
            fiber: 4,
            fat: 14,
            saturatedFat: 3,
            transFat: 0,
            cholesterol: 60,
            sodium: 700,
            potassium: 300,
            vitaminA: 6,
            vitaminC: 18,
            calcium: 5,
            iron: 8
        }
    },
    {
        id: 16,
        name: "Steamed Chicken Wheat Momos With Momo Chutney",
        description: "Serves 1 | Aromatic chicken mince encased in wheat wrapper. Served with momo chutney",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/7/45a44033-51c1-494e-984c-866a966e0b7b_cfdc282e-5300-4d43-af3c-292b5087089f.jpg_compressed",
        price: 229.0,
        type: "Non Veg",
        rating: "4.7",
        nutrition: {
            calories: 280,
            protein: 20,
            carbs: 30,
            sugars: 4,
            fiber: 5,
            fat: 10,
            saturatedFat: 2,
            transFat: 0,
            cholesterol: 50,
            sodium: 650,
            potassium: 280,
            vitaminA: 6,
            vitaminC: 15,
            calcium: 4,
            iron: 7
        }
    },
    {
        id: 91,
        name: "Chicken Personal Wok Bowl",
        description: "Serves 1 | Light eater - choice of any 1 rice/noodles, 1 sauce, 4 vegetables and 2 seasoning.",
        imageUrl: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/a0a65592fe99d652394070a6a9420259",
        price: 339.0,
        type: "Non Veg",
        rating: "4.0",
        nutrition: {
            calories: 360,
            protein: 24,
            carbs: 40,
            sugars: 10,
            fiber: 6,
            fat: 14,
            saturatedFat: 4,
            transFat: 0,
            cholesterol: 65,
            sodium: 850,
            potassium: 370,
            vitaminA: 8,
            vitaminC: 22,
            calcium: 5,
            iron: 10
        }
    }
];
export default Datas
